apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: inventory-manager
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/adamstevey/inventory-manager:frontend
        ports:
        - containerPort: 3000
          name: http-frontend