name: backend CI

on:
  push:
    paths:
      - 'backend/**'

env:
  ENV_FILE: environment.properties

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: cardinalby/export-env-action@v1
        with:
          envFile: ${{ env.ENV_FILE }}
          expand: 'true'
      
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
      
      - name: build image
        id: build
        uses: docker/build-push-action@v3
        with:
          push: false
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/backend/Dockerfile
          tags: ${{ env.dockerhub_repo }}:backend-latest
          outputs: type=docker,dest=/tmp/image.tar 

      - uses: engineerd/setup-kind@v0.5.0
        with:
          wait: "30s"
          skipClusterDeletion: "true"
      - name: smoke test & load image
        run: |
          kubectl cluster-info
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kind load image-archive /tmp/image.tar --name kind
      
      - name: install kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          chmod +x ./kustomize
          mv ./kustomize /usr/local/bin
      
      - name: build kustomization & apply deployment
        run: |
          cd .github/backend_test
          kustomize edit set image CONTAINER_IMAGE=${{ env.dockerhub_repo }}:backend-latest
          kustomize build . | kubectl apply -f -
          echo "Waiting for pod to start..."
          sleep 60
          kubectl get pods
          kubectl describe pod test

